"""Verify and durably retain the bounded Linux accounting run; no new guest run."""
import argparse
import hashlib
import json
from pathlib import Path
import tempfile
import zipfile

from accounting import generation, make_plan, summarize
from cli_result import classify
from inventory import MANIFEST, sha256

RUN = 34624439277
HEAD = "4e8a947300f6012d83b991017df4247cda06a449"
ARTIFACT_SHA256 = "08682429f62b8deaf656e1013dd1e11ad54795609353b48087f3810977cdbbd1"
OUTPUT = Path("docs/verification/a5-accounting-results.json")


def approved_plan(historical):
    """Rebind only approval metadata; prove every old semantic input byte matches."""
    current = make_plan(json.loads(MANIFEST.read_text()))
    previous = {**current, "status": "proposed-not-frozen"}
    for key, path in (("inventory_sha256", MANIFEST),
                      ("profile_sha256", Path("scripts/a5/profile-proposal.json"))):
        data = path.read_bytes()
        marker = b'"status": "approved-frozen"'
        if data.count(marker) != 1:
            raise ValueError("approval status must occur exactly once")
        previous[key] = hashlib.sha256(data.replace(
            marker, b'"status": "proposed-not-frozen"')).hexdigest()
    if previous != historical:
        raise ValueError("historical inputs differ beyond approval status")
    return current


def replay(archive, *, final=False):
    run = 34766332271 if final else RUN
    head = "f2edf77f17a76bea3d7062f40f5f4f38ad4eb580" if final else HEAD
    artifact = ({"id": 10320897156,
                 "sha256": "bb851d5486d16fe47d68fcc757f610fda7f1d2e3a2c431848dea35b7b514beb9",
                 "expires_at": "2026-09-27T15:45:37Z", "bytes": 21675966} if final else
                {"id": 10274071547, "sha256": ARTIFACT_SHA256,
                 "expires_at": "2026-09-25T16:56:08Z", "bytes": 21676628})
    if sha256(archive) != artifact["sha256"] or archive.stat().st_size != artifact["bytes"]:
        raise ValueError("retained artifact differs from recorded Linux run")
    with tempfile.TemporaryDirectory(dir=".a5") as directory:
        root = Path(directory)
        with zipfile.ZipFile(archive) as bundle:
            # This exact hash-verified archive was generated by our workflow.
            bundle.extractall(root)
        evidence = root / "evidence"
        historical_plan = json.loads((evidence / "selection-plan.json").read_text())
        plan = approved_plan(historical_plan)
        original = json.loads((evidence / "selection-results.json").read_text())
        if sha256(evidence / "selection-plan.json") != original["plan_sha256"]:
            raise ValueError("retained plan hash differs")
        for name, digest in original["configuration_sha256"].items():
            relative = Path(name).relative_to(".a5")
            if sha256(root / relative) != digest:
                raise ValueError("retained configuration hash differs")
            source = Path("scripts/a5") / relative.name
            if source.is_file():
                expected = source.read_bytes()
                if source.name == "ruscv-rv64i-smoke.yaml":
                    runner_root = Path(original["results"][0]["command"][0]).parents[2]
                    expected += f"arch_overlay: {json.dumps(str(runner_root / '.a5/config/overlay'))}\n".encode()
                if hashlib.sha256(expected).hexdigest() != digest:
                    raise ValueError("current executable configuration differs")
        generated = generation(plan, root / "work", 0)
        generated["status"] = historical_plan["status"]
        if generated["errors"]:
            raise ValueError(generated["errors"])
        results = original["results"]
        diagnostics = {}
        for result in results:
            prefix = evidence / "cli" / result["elf"]
            stdout = Path(str(prefix) + ".stdout.txt").read_text()
            stderr = Path(str(prefix) + ".stderr.txt").read_text()
            classified = classify(stdout, stderr, result["returncode"], max_cycles=result["max_cycles"])
            if any(classified[key] != result[key] for key in classified):
                raise ValueError("strict classifier replay differs")
            audit = json.loads((evidence / "audit" / result["elf"] / "audit.json").read_text())
            if not audit["instructions"] or audit["unsupported"]:
                raise ValueError("retained linked audit failed")
            diagnostics[result["source"]] = {"stdout": stdout, "stderr": stderr, "audit": audit}
        summary = summarize(plan, generated, results)
        summary["status"] = historical_plan["status"]
        if summary != original["summary"] or original["simulator_revision"] != head:
            raise ValueError("retained summary/head differs")
        if final and not summary["success"]:
            raise ValueError("final selection did not pass")
        # Reapply fail-closed accounting to REAL generated identities/results.
        controls = {}
        for name, changed in {
            "empty-results": [], "missing-result": results[:-1],
            "duplicate-result": results + results[:1],
            "extra-result": results + [{**results[0], "elf": "extra.elf"}],
        }.items():
            check = summarize(plan, generated, changed)
            controls[name] = any("execution results" in error for error in check["errors"])
        failed_generation = generation(plan, root / "work", 1)
        controls["generation-command-failed"] = any("generation command failed" in error for error in failed_generation["errors"])
        for key in ("elf", "signature_elf", "signature", "expected_results"):
            target = root / "work" / plan["variants"][0][key]
            original_bytes = target.read_bytes()
            target.unlink()
            controls["missing-" + key] = bool(generation(plan, root / "work", 0)["errors"])
            target.write_bytes(original_bytes)
        for suffix in (".elf", ".sig", ".results"):
            target = root / "work" / ("extra" + suffix)
            target.write_bytes(b"unexpected output")
            controls["extra" + suffix] = bool(generation(plan, root / "work", 0)["errors"])
            target.unlink()
        if not all(controls.values()):
            raise ValueError("retained accounting negative control falsely accepted")
        guest_controls = json.loads((evidence / "controls/results.json").read_text())
        for result in guest_controls["results"]:
            prefix = evidence / "controls" / result["control"]
            stdout, stderr = Path(str(prefix) + ".stdout.txt").read_text(), Path(str(prefix) + ".stderr.txt").read_text()
            classified = classify(stdout, stderr, result["returncode"], max_cycles=result["max_cycles"])
            if any(classified[key] != result[key] for key in classified):
                raise ValueError("guest control replay differs")
            result.update({"stdout": stdout, "stderr": stderr})
        if not guest_controls["success"]:
            raise ValueError("public guest controls failed")
        report = {"status": "approved-frozen-suite-passed" if final else "proposed-not-frozen-suite-failed",
                "run": run, "head": head, "artifact": artifact,
                "tool_versions": (evidence / "versions.txt").read_text(),
                "overlay": json.loads((evidence / "overlay.json").read_text()),
                "profile_identity": {k: v for k, v in historical_plan.items() if k != "variants"},
                "generation": generated, "execution": original, "diagnostics": diagnostics,
                "public_guest_controls": guest_controls,
                "local_retained_accounting_controls": controls,
                "replay_scope": "artifact hashes, strict CLI parser and complete accounting only; no new generation or guest execution"}
        if final:
            report["approval"] = {
                "date": "2026-09-15",
                "record": "docs/verification/a5-selection-proposal.md#final-decision-and-evidence",
                "change": "status bytes only; historical plan and input hashes verified by approved_plan",
                "current_profile_identity": {k: v for k, v in plan.items() if k != "variants"},
            }
        return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archive", type=Path)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--final", action="store_true", help="replay the final 51-pass merge-head artifact")
    args = parser.parse_args()
    report = replay(args.archive, final=args.final)
    output = Path("docs/verification/a5-final-results.json") if args.final else OUTPUT
    if args.write:
        output.write_text(json.dumps(report, indent=2) + "\n")
    elif json.loads(output.read_text()) != report:
        raise ValueError("durable evidence differs from artifact replay")
    print(json.dumps({"summary": report["execution"]["summary"],
                      "negative_controls": report["local_retained_accounting_controls"]}, indent=2))


if __name__ == "__main__":
    main()
