"""Verify and durably retain the bounded Linux accounting run; no new guest run."""
import argparse
import json
from pathlib import Path
import tempfile
import zipfile

from accounting import generation, summarize
from cli_result import classify
from inventory import sha256

RUN = 34624439277
HEAD = "4e8a947300f6012d83b991017df4247cda06a449"
ARTIFACT_SHA256 = "08682429f62b8deaf656e1013dd1e11ad54795609353b48087f3810977cdbbd1"
OUTPUT = Path("docs/verification/a5-accounting-results.json")


def replay(archive):
    if sha256(archive) != ARTIFACT_SHA256:
        raise ValueError("retained artifact differs from recorded Linux run")
    with tempfile.TemporaryDirectory(dir=".a5") as directory:
        root = Path(directory)
        with zipfile.ZipFile(archive) as bundle:
            # This exact hash-verified archive was generated by our workflow.
            bundle.extractall(root)
        evidence = root / "evidence"
        plan = json.loads((evidence / "selection-plan.json").read_text())
        original = json.loads((evidence / "selection-results.json").read_text())
        generated = generation(plan, root / "work", 0)
        if generated["errors"]:
            raise ValueError(generated["errors"])
        results = original["results"]
        diagnostics = {}
        for result in results:
            prefix = evidence / "cli" / result["elf"]
            stdout = Path(str(prefix) + ".stdout.txt").read_text()
            stderr = Path(str(prefix) + ".stderr.txt").read_text()
            classified = classify(stdout, stderr, result["returncode"], max_cycles=result["max_cycles"])
            if any(classified[key] != result[key] for key in classified):
                raise ValueError("strict classifier replay differs")
            audit = json.loads((evidence / "audit" / result["elf"] / "audit.json").read_text())
            if not audit["instructions"] or audit["unsupported"]:
                raise ValueError("retained linked audit failed")
            diagnostics[result["source"]] = {"stdout": stdout, "stderr": stderr, "audit": audit}
        summary = summarize(plan, generated, results)
        if summary != original["summary"] or original["simulator_revision"] != HEAD:
            raise ValueError("retained summary/head differs")
        # Reapply fail-closed accounting to REAL generated identities/results.
        controls = {}
        for name, changed in {
            "empty-results": [], "missing-result": results[:-1],
            "duplicate-result": results + results[:1],
            "extra-result": results + [{**results[0], "elf": "extra.elf"}],
        }.items():
            check = summarize(plan, generated, changed)
            controls[name] = any("execution results" in error for error in check["errors"])
        failed_generation = generation(plan, root / "work", 1)
        controls["generation-command-failed"] = any("generation command failed" in error for error in failed_generation["errors"])
        for key in ("elf", "signature_elf", "signature", "expected_results"):
            target = root / "work" / plan["variants"][0][key]
            original_bytes = target.read_bytes()
            target.unlink()
            controls["missing-" + key] = bool(generation(plan, root / "work", 0)["errors"])
            target.write_bytes(original_bytes)
        for suffix in (".elf", ".sig", ".results"):
            target = root / "work" / ("extra" + suffix)
            target.write_bytes(b"unexpected output")
            controls["extra" + suffix] = bool(generation(plan, root / "work", 0)["errors"])
            target.unlink()
        if not all(controls.values()):
            raise ValueError("retained accounting negative control falsely accepted")
        guest_controls = json.loads((evidence / "controls/results.json").read_text())
        for result in guest_controls["results"]:
            prefix = evidence / "controls" / result["control"]
            stdout, stderr = Path(str(prefix) + ".stdout.txt").read_text(), Path(str(prefix) + ".stderr.txt").read_text()
            classified = classify(stdout, stderr, result["returncode"], max_cycles=result["max_cycles"])
            if any(classified[key] != result[key] for key in classified):
                raise ValueError("guest control replay differs")
            result.update({"stdout": stdout, "stderr": stderr})
        return {"status": "proposed-not-frozen-suite-failed", "run": RUN, "head": HEAD,
                "artifact": {"id": 10274071547, "sha256": ARTIFACT_SHA256,
                             "expires_at": "2026-09-25T16:56:08Z", "bytes": 21676628},
                "tool_versions": (evidence / "versions.txt").read_text(),
                "overlay": json.loads((evidence / "overlay.json").read_text()),
                "profile_identity": {k: v for k, v in plan.items() if k != "variants"},
                "generation": generated, "execution": original, "diagnostics": diagnostics,
                "public_guest_controls": guest_controls,
                "local_retained_accounting_controls": controls,
                "replay_scope": "artifact hashes, strict CLI parser and complete accounting only; no new generation or guest execution"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archive", type=Path)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    report = replay(args.archive)
    if args.write:
        OUTPUT.write_text(json.dumps(report, indent=2) + "\n")
    elif json.loads(OUTPUT.read_text()) != report:
        raise ValueError("durable evidence differs from artifact replay")
    print(json.dumps({"summary": report["execution"]["summary"],
                      "negative_controls": report["local_retained_accounting_controls"]}, indent=2))


if __name__ == "__main__":
    main()
