//! Trap handling framework
//!
//! Implements RISC-V trap (exception + interrupt) handling mechanisms:
//! - Trap type enum (Exception + Interrupt)
//! - Trap handling framework
//! - mtvec, mepc, mcause, mstatus CSR integration
//!
//! # Trap Categories
//!
//! **Synchronous Exceptions**: Generated by instruction execution
//! - Misaligned address
//! - Access fault
//! - Illegal instruction
//! - Breakpoint
//! - Environment call
//!
//! **Interrupts**: Asynchronous events from external sources
//! - Machine software interrupt (MSI)
//! - Machine timer interrupt (MTI)
//! - Machine external interrupt (MEI)
//! - Supervisor software/timer/external interrupts

use crate::core::{CoreState, PrivilegeMode};
use crate::csr::machine;
use crate::csr::supervisor;
use crate::csr::CsrFile;

/// RISC-V trap cause
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Trap {
    /// Exception with cause code
    Exception(ExceptionCause),
    /// Interrupt with cause code (bit 31 set)
    Interrupt(InterruptCause),
}

/// Exception cause codes (RISC-V Privileged Spec)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExceptionCause {
    /// 0 - Instruction address misaligned
    InstructionAddressMisaligned = 0,
    /// 1 - Instruction access fault
    InstructionAccessFault = 1,
    /// 2 - Illegal instruction
    IllegalInstruction = 2,
    /// 3 - Breakpoint
    Breakpoint = 3,
    /// 4 - Load address misaligned
    LoadAddressMisaligned = 4,
    /// 5 - Load access fault
    LoadAccessFault = 5,
    /// 6 - Store/AMO address misaligned
    StoreAddressMisaligned = 6,
    /// 7 - Store/AMO access fault
    StoreAccessFault = 7,
    /// 8 - Environment call from U-mode
    EcallU = 8,
    /// 9 - Environment call from S-mode
    EcallS = 9,
    /// 11 - Environment call from M-mode
    EcallM = 11,
    /// 12 - Instruction page fault
    InstructionPageFault = 12,
    /// 13 - Load page fault
    LoadPageFault = 13,
    /// 15 - Store/AMO page fault
    StorePageFault = 15,
}

impl ExceptionCause {
    /// Check if this is an access fault (non-page fault)
    pub fn is_access_fault(self) -> bool {
        matches!(
            self,
            Self::InstructionAccessFault | Self::LoadAccessFault | Self::StoreAccessFault
        )
    }

    /// Check if this is a page fault
    pub fn is_page_fault(self) -> bool {
        matches!(
            self,
            Self::InstructionPageFault | Self::LoadPageFault | Self::StorePageFault
        )
    }

    /// Check if this is an ECALL exception
    pub fn is_ecall(self) -> bool {
        matches!(self, Self::EcallU | Self::EcallS | Self::EcallM)
    }

    /// Get exception code value for mcause
    pub fn code(self) -> u64 {
        self as u64
    }
}

/// Interrupt cause codes (RISC-V Privileged Spec)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InterruptCause {
    /// 0 - User software interrupt
    UserSoftware = 0,
    /// 1 - Supervisor software interrupt
    SupervisorSoftware = 1,
    /// 3 - Machine software interrupt
    MachineSoftware = 3,
    /// 4 - User timer interrupt
    UserTimer = 4,
    /// 5 - Supervisor timer interrupt
    SupervisorTimer = 5,
    /// 7 - Machine timer interrupt
    MachineTimer = 7,
    /// 8 - User external interrupt
    UserExternal = 8,
    /// 9 - Supervisor external interrupt
    SupervisorExternal = 9,
    /// 11 - Machine external interrupt
    MachineExternal = 11,
}

impl InterruptCause {
    /// Get interrupt code value for mcause (with bit 31 set)
    pub fn code(self) -> u64 {
        (1 << 63) | (self as u64)
    }

    /// Check if this is a machine mode interrupt
    pub fn is_machine_mode(self) -> bool {
        matches!(
            self,
            Self::MachineSoftware | Self::MachineTimer | Self::MachineExternal
        )
    }

    /// Check if this is a supervisor mode interrupt
    pub fn is_supervisor_mode(self) -> bool {
        matches!(
            self,
            Self::SupervisorSoftware | Self::SupervisorTimer | Self::SupervisorExternal
        )
    }
}

/// Trap delegation configuration
#[derive(Debug)]
pub struct TrapDelegation {
    /// Exception delegation to supervisor
    pub medeleg: u32,
    /// Interrupt delegation to supervisor
    pub mideleg: u32,
}

impl TrapDelegation {
    /// Create new delegation configuration
    pub fn new() -> Self {
        Self {
            medeleg: 0,
            mideleg: 0,
        }
    }

    /// Check if exception should be delegated to supervisor
    pub fn should_delegate_exception(&self, cause: ExceptionCause) -> bool {
        (self.medeleg >> (cause as u32)) & 1 == 1
    }

    /// Check if interrupt should be delegated to supervisor
    pub fn should_delegate_interrupt(&self, cause: InterruptCause) -> bool {
        (self.mideleg >> (cause as u32)) & 1 == 1
    }

    /// Delegate exception to supervisor
    pub fn delegate_exception(&mut self, cause: ExceptionCause) {
        self.medeleg |= 1 << (cause as u32);
    }

    /// Delegate interrupt to supervisor
    pub fn delegate_interrupt(&mut self, cause: InterruptCause) {
        self.mideleg |= 1 << (cause as u32);
    }
}

impl Default for TrapDelegation {
    fn default() -> Self {
        Self::new()
    }
}

/// Trap handling context
#[derive(Debug)]
pub struct TrapContext {
    /// Program counter at time of trap
    pub epc: u32,
    /// Trap cause
    pub cause: u64,
    /// Trap value (faulting address or instruction)
    pub tval: u32,
    /// Privilege mode at time of trap
    pub privilege: PrivilegeMode,
}

impl TrapContext {
    /// Create new trap context
    pub fn new(epc: u32, cause: u64, tval: u32, privilege: PrivilegeMode) -> Self {
        Self {
            epc,
            cause,
            tval,
            privilege,
        }
    }
}

/// Trap handler
#[derive(Debug)]
pub struct TrapHandler {
    /// Trap delegation configuration
    delegation: TrapDelegation,
}

impl TrapHandler {
    /// Create new trap handler
    pub fn new() -> Self {
        Self {
            delegation: TrapDelegation::new(),
        }
    }

    /// Handle a trap
    ///
    /// # Arguments
    /// * `trap` - The trap that occurred
    /// * `epc` - Current program counter
    /// * `tval` - Trap value (faulting address/instruction)
    /// * `state` - Core state to update
    ///
    /// # Returns
    /// The new PC to jump to (from mtvec/stvec)
    pub fn handle_trap(&mut self, trap: Trap, epc: u32, tval: u32, state: &mut CoreState) -> u32 {
        // Determine which mode handles this trap
        let (target_mode, _delegatable) = match trap {
            Trap::Exception(cause) => {
                let delegatable = self.delegation.should_delegate_exception(cause);
                if delegatable && state.privilege != PrivilegeMode::Machine {
                    (PrivilegeMode::Supervisor, true)
                } else {
                    (PrivilegeMode::Machine, false)
                }
            }
            Trap::Interrupt(cause) => {
                let delegatable = self.delegation.should_delegate_interrupt(cause);
                if delegatable && state.privilege != PrivilegeMode::Machine {
                    (PrivilegeMode::Supervisor, true)
                } else {
                    (PrivilegeMode::Machine, false)
                }
            }
        };

        // Set up trap CSRs based on target mode
        let cause_value = match trap {
            Trap::Exception(cause) => cause.code(),
            Trap::Interrupt(cause) => cause.code(),
        };

        match target_mode {
            PrivilegeMode::Machine => {
                state.csr.write(machine::MEPC, epc).ok();
                state.csr.write(machine::MCAUSE, cause_value as u32).ok();
                state.csr.write(machine::MTVAL, tval).ok();

                // Update mstatus: set MPIE = MIE, set MIE = 0, set MPP = current mode
                let mstatus = state.csr.read(machine::MSTATUS).unwrap_or(0);
                let _mpie = (mstatus >> 7) & 1;
                let mie = (mstatus >> 3) & 1;
                let mpp = state.privilege as u32;

                let new_mstatus = (mstatus & !0x1888) // Clear MIE, MPIE, MPP
                    | (mie << 7)      // MPIE = old MIE
                    | (mpp << 11); // MPP = current mode

                state.csr.write(machine::MSTATUS, new_mstatus).ok();
                state.privilege = PrivilegeMode::Machine;

                // Vector to trap handler
                let mtvec = state.csr.read(machine::MTVEC).unwrap_or(0);
                self.vector_trap(mtvec, cause_value)
            }
            PrivilegeMode::Supervisor => {
                state.csr.write(supervisor::SEPC, epc).ok();
                state.csr.write(supervisor::SCAUSE, cause_value as u32).ok();
                state.csr.write(supervisor::STVAL, tval).ok();

                // Update sstatus: set SPIE = SIE, set SIE = 0, set SPP = current mode
                let sstatus = state.csr.read(supervisor::SSTATUS).unwrap_or(0);
                let _spie = (sstatus >> 5) & 1;
                let sie = (sstatus >> 1) & 1;
                let spp = if state.privilege == PrivilegeMode::Supervisor {
                    1
                } else {
                    0
                };

                let new_sstatus = (sstatus & !0x222) // Clear SIE, SPIE, SPP
                    | (sie << 5)    // SPIE = old SIE
                    | (spp << 8); // SPP = current mode

                state.csr.write(supervisor::SSTATUS, new_sstatus).ok();
                state.privilege = PrivilegeMode::Supervisor;

                // Vector to trap handler
                let stvec = state.csr.read(supervisor::STVEC).unwrap_or(0);
                self.vector_trap(stvec, cause_value)
            }
            PrivilegeMode::User => {
                // User mode traps are always delegated to supervisor
                // This shouldn't normally happen without delegation
                epc
            }
        }
    }

    /// Calculate vectored trap address
    pub fn vector_trap(&self, tvec: u32, cause: u64) -> u32 {
        let mode = tvec & 0x3;
        let base = tvec & !0x3;

        match mode {
            0b00 => {
                // Direct mode: all traps go to base address
                base
            }
            0b01 => {
                // Vectored mode: add cause * 4 to base
                // For exceptions: cause = exception code
                // For interrupts: cause = interrupt code | 0x8000_0000_0000_0000
                let offset = (cause as u32 & 0x7F) << 2;
                base.wrapping_add(offset)
            }
            _ => base, // Reserved, use direct mode
        }
    }

    /// Get trap delegation configuration
    pub fn delegation(&self) -> &TrapDelegation {
        &self.delegation
    }

    /// Get mutable trap delegation configuration
    pub fn delegation_mut(&mut self) -> &mut TrapDelegation {
        &mut self.delegation
    }
}

impl Default for TrapHandler {
    fn default() -> Self {
        Self::new()
    }
}

/// Wrapper for core state to provide trap-specific methods
#[derive(Debug)]
pub struct CoreStateWrapper<'a> {
    /// Reference to CSR file
    pub csr: &'a mut CsrFile,
    /// Current privilege mode
    pub privilege: PrivilegeMode,
}

impl<'a> CoreStateWrapper<'a> {
    /// Create new wrapper
    pub fn new(csr: &'a mut CsrFile, privilege: PrivilegeMode) -> Self {
        Self { csr, privilege }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_exception_cause_codes() {
        assert_eq!(ExceptionCause::IllegalInstruction.code(), 2);
        assert_eq!(ExceptionCause::EcallM.code(), 11);
        assert_eq!(ExceptionCause::StoreAddressMisaligned.code(), 6);
    }

    #[test]
    fn test_interrupt_cause_codes() {
        // Interrupt codes have bit 63 set
        assert_eq!(
            InterruptCause::MachineSoftware.code(),
            0x8000_0000_0000_0003
        );
        assert_eq!(InterruptCause::MachineTimer.code(), 0x8000_0000_0000_0007);
        assert_eq!(
            InterruptCause::MachineExternal.code(),
            0x8000_0000_0000_000B
        );
    }

    #[test]
    fn test_exception_is_access_fault() {
        assert!(ExceptionCause::InstructionAccessFault.is_access_fault());
        assert!(ExceptionCause::LoadAccessFault.is_access_fault());
        assert!(ExceptionCause::StoreAccessFault.is_access_fault());
        assert!(!ExceptionCause::IllegalInstruction.is_access_fault());
    }

    #[test]
    fn test_exception_is_page_fault() {
        assert!(ExceptionCause::InstructionPageFault.is_page_fault());
        assert!(ExceptionCause::LoadPageFault.is_page_fault());
        assert!(ExceptionCause::StorePageFault.is_page_fault());
        assert!(!ExceptionCause::IllegalInstruction.is_page_fault());
    }

    #[test]
    fn test_trap_delegation() {
        let mut delegation = TrapDelegation::new();

        assert!(!delegation.should_delegate_exception(ExceptionCause::IllegalInstruction));
        assert!(!delegation.should_delegate_interrupt(InterruptCause::MachineSoftware));

        delegation.delegate_exception(ExceptionCause::IllegalInstruction);
        delegation.delegate_interrupt(InterruptCause::SupervisorSoftware);

        assert!(delegation.should_delegate_exception(ExceptionCause::IllegalInstruction));
        assert!(!delegation.should_delegate_interrupt(InterruptCause::MachineSoftware));
        assert!(delegation.should_delegate_interrupt(InterruptCause::SupervisorSoftware));
    }

    #[test]
    fn test_vector_trap_direct_mode() {
        let handler = TrapHandler::new();
        let tvec = 0x8000_0000; // Direct mode (bits [1:0] = 00)

        // Any cause should go to base address
        assert_eq!(handler.vector_trap(tvec, 0), 0x8000_0000);
        assert_eq!(handler.vector_trap(tvec, 7), 0x8000_0000);
    }

    #[test]
    fn test_vector_trap_vectored_mode() {
        let handler = TrapHandler::new();
        let tvec = 0x8000_0001; // Vectored mode (bits [1:0] = 01)

        // Cause should be multiplied by 4 and added to base
        assert_eq!(handler.vector_trap(tvec, 0), 0x8000_0000);
        assert_eq!(handler.vector_trap(tvec, 1), 0x8000_0004);
        assert_eq!(handler.vector_trap(tvec, 7), 0x8000_001C);
    }

    #[test]
    fn test_trap_context() {
        let ctx = TrapContext::new(0x1000, 2, 0xBAD0, PrivilegeMode::Machine);

        assert_eq!(ctx.epc, 0x1000);
        assert_eq!(ctx.cause, 2);
        assert_eq!(ctx.tval, 0xBAD0);
        assert_eq!(ctx.privilege, PrivilegeMode::Machine);
    }
}
