#!/usr/bin/env python3
"""
Log Comparison Tool for ruscv-sim vs Spike

Compares commit logs generated by ruscv-sim --log-commits and Spike --log-commits.
Outputs differences in register values at each PC address.

Usage:
    python3 log-compare.py <spike.log> <ruscv.log>
    python3 log-compare.py <spike.log> <ruscv.log> --verbose
    python3 log-compare.py <spike.log> <ruscv.log> --json > diff.json
    python3 log-compare.py <spike.log> <ruscv.log> --start-addr 0x80000000  # Only compare ELF entry point onwards
"""

import re
import sys
import json
from typing import Dict, List, Tuple, Optional, Any
from dataclasses import dataclass, field
from argparse import ArgumentParser


@dataclass
class RegisterChange:
    """Represents a register change at a specific PC"""
    pc: int
    opcode: int
    reg_name: str
    value: int
    source: str  # 'spike' or 'ruscv'


@dataclass
class InstructionEntry:
    """Represents an instruction execution entry"""
    pc: int
    opcode: int
    registers: Dict[str, int] = field(default_factory=dict)
    memory_access: Optional[Tuple[int, Optional[int], bool]] = None  # (addr, value, is_store)


class LogParser:
    """Parse Spike and ruscv-sim commit logs"""

    # Regex patterns matching Spike format
    # Spike format: core   0: 3 0x0000000080000000 (0x00000093) x1  0x0000000000000000
    INSTRUCTION_PATTERN = re.compile(
        r'core\s+\d+:\s*\d+\s+(0x[0-9a-f]+)\s+\((0x[0-9a-f]+)\)(.*)$'
    )
    REGISTER_PATTERN = re.compile(r'x(\d+)\s+(0x[0-9a-f]+)')
    MEMORY_PATTERN = re.compile(r'mem\s+([0-9a-f]+)(?:\s+([0-9a-f]+))?')
    COMMENT_PATTERN = re.compile(r'>>>>\s+(.+)')
    # Pattern to detect tohost write (typical tohost address: 0x80001000 or similar)
    TOHOST_PATTERN = re.compile(r'mem\s+(0x[0-9a-f]+)\s+([0-9a-f]+)')

    def __init__(self, verbose: bool = False, start_addr: Optional[int] = None,
                 stop_on_tohost: bool = True):
        self.verbose = verbose
        self.start_addr = start_addr  # Filter instructions below this address
        self.stop_on_tohost = stop_on_tohost  # Stop parsing after tohost write
        self.tohost_pc: Optional[int] = None  # PC where tohost was written

    def parse_instruction_line(self, line: str) -> Optional[Tuple[int, int, str, str]]:
        """Parse a single instruction line and return (hartid, pc, opcode, remaining)"""
        match = self.INSTRUCTION_PATTERN.match(line)
        if match:
            # Extract values from groups
            pc_str = match.group(1)
            opcode_str = match.group(2)
            remaining = match.group(3).strip()

            # Parse PC and opcode (remove 0x prefix for parsing)
            pc = int(pc_str, 16)
            opcode = int(opcode_str, 16)

            # Filter by start address (for ELF entry point filtering)
            if self.start_addr is not None and pc < self.start_addr:
                return None

            # Stop parsing if we hit tohost and stop_on_tohost is enabled
            if self.stop_on_tohost and self.tohost_pc is not None and pc > self.tohost_pc:
                return None

            if self.verbose:
                print(f"  [DEBUG] Parsed PC={pc:#x} opcode={opcode:#x}", file=sys.stderr)
            return (0, pc, opcode, remaining)  # hartid is 0 for single-core
        return None

    def detect_tohost(self, line: str) -> bool:
        """Detect tohost write in a line and set tohost_pc if found"""
        if self.tohost_pc is not None:
            return True  # Already found tohost

        # Check for tohost write (memory write to typical tohost address)
        # tohost is often at high addresses like 0x80001000 or similar
        match = self.TOHOST_PATTERN.search(line)
        if match:
            addr = int(match.group(1), 16)
            value = int(match.group(2), 16)
            # Common tohost patterns:
            # - Address 0x80001000 (typical riscv-tests tohost)
            # - Non-zero value being written (exit signal)
            # - Any write to high address (>= 0x80000000) with non-zero value
            if addr >= 0x80000000 and value != 0:
                # Extract PC from the line
                pc_match = self.INSTRUCTION_PATTERN.match(line)
                if pc_match:
                    pc = int(pc_match.group(1), 16)
                    self.tohost_pc = pc
                    if self.verbose:
                        print(f"  [INFO] Detected tohost-like write at PC={pc:#x}, addr={addr:#x}, value={value:#x}", file=sys.stderr)
                    return True
        return False

    def parse_register(self, text: str) -> Optional[Tuple[int, int]]:
        """Parse a register name and value from text"""
        match = self.REGISTER_PATTERN.search(text)
        if match:
            reg_num = int(match.group(1))
            value_str = match.group(2)
            value = int(value_str, 16)
            return (reg_num, value)
        return None

    def parse_memory(self, text: str) -> Optional[Tuple[int, Optional[int], bool]]:
        """Parse memory access info from text, return (addr, value, is_store)"""
        match = self.MEMORY_PATTERN.search(text)
        if match:
            addr = int(match.group(1), 16)
            value_str = match.group(2)
            value = int(value_str, 16) if value_str else None
            is_store = value is not None
            return (addr, value, is_store)
        return None

    def parse_file(self, filepath: str) -> Dict[int, InstructionEntry]:
        """
        Parse a log file and return a dict mapping PC -> InstructionEntry
        """
        entries: Dict[int, InstructionEntry] = {}

        with open(filepath, 'r') as f:
            for line_num, line in enumerate(f, 1):
                line = line.rstrip()

                # Skip empty lines and comments
                if not line or line.startswith('>>>>'):
                    continue

                # Detect tohost write (and stop parsing after if enabled)
                if self.detect_tohost(line):
                    if self.stop_on_tohost and self.verbose:
                        print(f"  [INFO] Stopping parse at tohost write (line {line_num})", file=sys.stderr)
                    if self.stop_on_tohost:
                        break
                    continue

                # Try to parse as instruction line
                result = self.parse_instruction_line(line)
                if result is None:
                    if self.verbose:
                        print(f"  [WARN] Line {line_num}: Could not parse: {line[:50]}...", file=sys.stderr)
                    continue

                hartid, pc, opcode, remaining = result

                # Create or update entry for this PC
                if pc not in entries:
                    entries[pc] = InstructionEntry(pc=pc, opcode=opcode)
                entry = entries[pc]

                # Parse registers from remaining text
                reg_match = self.parse_register(remaining)
                if reg_match:
                    reg_num, value = reg_match
                    reg_name = f'x{reg_num}'
                    entry.registers[reg_name] = value
                    if self.verbose:
                        print(f"  [DEBUG] PC={pc:#x}: {reg_name}={value:#x}", file=sys.stderr)

                # Parse memory access
                mem_match = self.parse_memory(remaining)
                if mem_match:
                    addr, value, is_store = mem_match
                    entry.memory_access = (addr, value, is_store)

        if self.verbose:
            print(f"  [INFO] Parsed {len(entries)} unique PCs from {filepath}", file=sys.stderr)
            if self.tohost_pc:
                print(f"  [INFO] Stopped at tohost PC={self.tohost_pc:#x}", file=sys.stderr)

        return entries


class LogComparator:
    """Compare two parsed log entries and find differences"""

    def __init__(self, spike_data: Dict[int, InstructionEntry],
                 ruscv_data: Dict[int, InstructionEntry]):
        self.spike_data = spike_data
        self.ruscv_data = ruscv_data

    def compare(self) -> List[Dict[str, Any]]:
        """
        Compare the two datasets and return a list of differences

        Returns a list of dicts, each containing:
        - pc: The program counter where difference was found
        - opcode: The instruction opcode
        - spike_regs: Registers from spike
        - ruscv_regs: Registers from ruscv
        - diffs: List of (reg_name, spike_val, ruscv_val) tuples
        """
        differences = []

        # Get common PCs (only compare PCs that exist in both logs)
        # This naturally handles the case where one sim exits earlier
        common_pcs = set(self.spike_data.keys()) & set(self.ruscv_data.keys())

        for pc in sorted(common_pcs):
            spike_entry = self.spike_data.get(pc)
            ruscv_entry = self.ruscv_data.get(pc)

            # Both entries should exist since we're iterating common PCs
            if spike_entry is None or ruscv_entry is None:
                continue
                differences.append({
                    'pc': pc,
                    'opcode': ruscv_entry.opcode if ruscv_entry else 0,
                    'spike_regs': {},
                    'ruscv_regs': ruscv_entry.registers if ruscv_entry else {},
                    'diffs': [{'reg': 'MISSING', 'spike': None, 'ruscv': ruscv_entry.registers}],
                    'note': 'PC exists only in ruscv'
                })
                continue

            if ruscv_entry is None:
                differences.append({
                    'pc': pc,
                    'opcode': spike_entry.opcode,
                    'spike_regs': spike_entry.registers,
                    'ruscv_regs': {},
                    'diffs': [{'reg': 'MISSING', 'spike': spike_entry.registers, 'ruscv': None}],
                    'note': 'PC exists only in spike'
                })
                continue

            # Compare registers at this PC
            all_regs = set(spike_entry.registers.keys()) | set(ruscv_entry.registers.keys())
            pc_diffs = []

            for reg in sorted(all_regs):
                spike_val = spike_entry.registers.get(reg)
                ruscv_val = ruscv_entry.registers.get(reg)

                # =====================================================================
                # LOGGING STRATEGY DIFFERENCE (not a functional bug):
                #
                # Spike: Logs ALL register writes, including xN=0 (even if already 0)
                # ruscv-sim: Only logs CHANGED registers (skips xN if value didn't change)
                #
                # When spike has "x5  0x0000000000000000" but ruscv has nothing,
                # BOTH mean the register value is 0 - this is NOT a difference!
                #
                # Example:
                #   Spike: "x5  0x0" (explicitly wrote 0 to x5)
                #   ruscv-sim: (nothing) (x5 was already 0, no change logged)
                #   Result: EQUIVALENT - both show register is 0
                # =====================================================================
                if spike_val == 0 and ruscv_val is None:
                    continue

                if spike_val != ruscv_val:
                    pc_diffs.append({
                        'reg': reg,
                        'spike': spike_val,
                        'ruscv': ruscv_val
                    })

            if pc_diffs:
                differences.append({
                    'pc': pc,
                    'opcode': spike_entry.opcode,
                    'spike_regs': spike_entry.registers,
                    'ruscv_regs': ruscv_entry.registers,
                    'diffs': pc_diffs,
                    'note': ''
                })

        return differences


def format_output(differences: List[Dict[str, Any]], output_format: str = 'text') -> str:
    """Format differences for output"""
    if output_format == 'json':
        return json.dumps(differences, indent=2)

    lines = []

    if not differences:
        return "✅ No differences found!"

    lines.append(f"❌ Differences found in {len(differences)} instruction(s):")
    lines.append("")

    for diff in differences:
        pc = diff['pc']
        opcode = diff['opcode']
        pc_diffs = diff['diffs']

        lines.append(f"PC {pc:#018x} (opcode {opcode:#010x}):")
        lines.append(f"  Spike:  {format_registers(diff['spike_regs'])}")
        lines.append(f"  ruscv:  {format_registers(diff['ruscv_regs'])}")
        lines.append("  Differences:")
        for d in pc_diffs:
            reg = d['reg']
            spike_val = d['spike']
            ruscv_val = d['ruscv']

            if spike_val is None:
                lines.append(f"    {reg}: spike=<missing>, ruscv={ruscv_val:#x}" if isinstance(ruscv_val, int) else f"    {reg}: spike=<missing>, ruscv={ruscv_val}")
            elif ruscv_val is None:
                lines.append(f"    {reg}: spike={spike_val:#x}, ruscv=<missing>" if isinstance(spike_val, int) else f"    {reg}: spike={spike_val}, ruscv=<missing>")
            else:
                spike_str = f"{spike_val:#x}" if isinstance(spike_val, int) else str(spike_val)
                ruscv_str = f"{ruscv_val:#x}" if isinstance(ruscv_val, int) else str(ruscv_val)
                lines.append(f"    {reg}: spike={spike_str}, ruscv={ruscv_str}")

        if diff.get('note'):
            lines.append(f"  Note: {diff['note']}")
        lines.append("")

    return "\n".join(lines)


def format_registers(regs: Dict[str, int]) -> str:
    """Format a dict of registers as a readable string"""
    if not regs:
        return "(no registers)"
    parts = [f"{k}={v:#x}" for k, v in sorted(regs.items(), key=lambda x: int(x[0][1:]))]
    return ", ".join(parts)


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description='Compare ruscv-sim and Spike commit logs',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  %(prog)s spike.log ruscv.log
  %(prog)s spike.log ruscv.log --verbose
  %(prog)s spike.log ruscv.log --json > diff.json
  %(prog)s spike.log ruscv.log --start-addr 0x80000000  # Only compare ELF entry point
  %(prog)s spike.log ruscv.log --no-stop-tohost  # Don't stop at tohost write

Format examples:
  spike.log:     core   0: 3 0x0000000080000000 (0x00000093) x1  0x0000000000000000
  ruscv.log:     core   0: 3 0x0000000080000000 (0x00000093) x1  0x0000000000000000
'''
    )
    parser.add_argument('spike_log', help='Path to Spike log file')
    parser.add_argument('ruscv_log', help='Path to ruscv-sim log file')
    parser.add_argument('--verbose', '-v', action='store_true', help='Enable verbose output')
    parser.add_argument('--json', action='store_true', help='Output in JSON format')
    parser.add_argument('--start-addr', '-s', type=lambda x: int(x, 16),
                        help='Only compare instructions at or above this address (hex, e.g., 0x80000000)')
    parser.add_argument('--no-stop-tohost', action='store_true',
                        help='Don\'t stop comparison at tohost write (default: stop)')

    args = parser.parse_args()

    # Parse both log files
    stop_on_tohost = not args.no_stop_tohost
    spike_parser = LogParser(verbose=args.verbose, start_addr=args.start_addr, stop_on_tohost=stop_on_tohost)
    ruscv_parser = LogParser(verbose=args.verbose, start_addr=args.start_addr, stop_on_tohost=stop_on_tohost)

    if args.verbose:
        print(f"Parsing Spike log: {args.spike_log}", file=sys.stderr)
        if args.start_addr:
            print(f"Filtering instructions below {args.start_addr:#018x}", file=sys.stderr)
        if stop_on_tohost:
            print("Stopping at tohost write", file=sys.stderr)
    spike_data = spike_parser.parse_file(args.spike_log)

    if args.verbose:
        print(f"Parsing ruscv-sim log: {args.ruscv_log}", file=sys.stderr)
    ruscv_data = ruscv_parser.parse_file(args.ruscv_log)

    # Compare
    comparator = LogComparator(spike_data, ruscv_data)
    differences = comparator.compare()

    # Output
    output_format = 'json' if args.json else 'text'
    result = format_output(differences, output_format)
    print(result)

    # Return exit code based on differences
    sys.exit(1 if differences else 0)


if __name__ == '__main__':
    main()
